apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      name: python-app
      labels:
        app: python-app
    spec:
      containers:
       - name: flask-container
         image: flask-image
         imagePullPolicy: IfNotPresent
         ports:
          - containerPort: 5000
