---
- name: Install Softwares method 1
  hosts: localhost
  become: true
  tasks:
   - name: Intall Items
     apt: 
       name: {{item}}
       state: present
       with_items:
        - apache2
        - nginx
  - name: Stopping apache2
    serivce: 
      name: apache2
      state: stopped
  - name: Stopping nginx
    service:
      name: nginx
      state: stopped

---
- name: Install Softwares method 2
  hosts: localhost
  become: true
  vars:
    packages:
     - name: nginx
       required: true
     - name: apache2
       required: true
  tasks:
   - name: Install items
     apt:
       name: {{item.name}}
       state: present
       when: item.required == true
       loop: {{packages}}

  